/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.khoa.base64.java;

import org.junit.Test;

public class Base64LibJavaTest {
  @Test
  public void someLibraryMethodReturnsTrue() {
    Base64LibJava.encode("");
    Base64LibJava.decode("");
  }
}
